### ISSUE TITLE
电信更新了，现在全部都无法登录了，有新的方案吗

### ISSUE THREAD

**Issue by arvinsblog** [Cp0204/ChinaTelecomMonitor#15]
![image](https://github.com/user-attachments/assets/ca3126ed-ccfa-4749-b1c0-62fcf6da14f3)

**Comment by Cp0204** [comment]
請充分排除自身問題再提出 Issue

![image](https://github.com/user-attachments/assets/3f65fb28-a815-4221-92dc-1eca1bc67264)
