### ISSUE TITLE
不限量套查询流量报错

### ISSUE THREAD

**Issue by 457084333** [Cp0204/ChinaTelecomMonitor#16]
不限量套查询流量报错，非不限量套餐可以查询。请帮忙看下是出了什么问题，谢谢
<img width="392" alt="Snipaste_2024-12-03_19-35-05" src="https://github.com/user-attachments/assets/a06a5eb8-169e-4317-8820-8fd5fd850fec">
<img width="467" alt="Snipaste_2024-12-03_19-35-36" src="https://github.com/user-attachments/assets/bc76d94d-8189-4f51-af9d-fb3ff252009a">

===============程序开始===============
⏰ 执行时间: 2024-12-03 00:04:45

自动登录：***********
自动登录：成功
获取主要信息：成功
Traceback (most recent call last):
  File "/ql/data/scripts/ChinaTelecomMonitor/telecom_monitor.py", line 194, in <module>
    main()
  File "/ql/data/scripts/ChinaTelecomMonitor/telecom_monitor.py", line 127, in main
    summary = telecom.to_summary(important_data["responseData"]["data"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/ChinaTelecomMonitor/telecom_class.py", line 212, in to_summary
    common_total = common_use + common_balance
                                ^^^^^^^^^^^^^^
NameError: name 'common_balance' is not defined. Did you mean: 'voice_balance'?

## 执行结束... 2024-12-03 00:04:48  耗时 4 秒

===============程序开始===============
⏰ 执行时间: 2024-12-02 23:59:58

⚙️ 正从 telecom_config.json 文件中读取配置
自动登录：***********
自动登录：成功
获取主要信息：成功
简化主要信息：{'phonenum': '**********', 'balance': 6402, 'voiceUsage': 0, 'voiceTotal': 100, 'flowUse': 0, 'flowTotal': 21585920, 'flowOver': 0, 'commonUse': 0, 'commonTotal': 21585920, 'commonOver': 0, 'specialUse': 0, 'specialTotal': 0, 'createTime': '2024-12-02 23:59:59', 'flowItems': [{'name': '国内通用流量', 'use': 0, 'balance': 21590179, 'total': 21590179}]}
获取流量包明细：成功
📢 📱 手机：**************
💰 余额：64.02
📞 通话：0 / 100 min
🌐 总流量
  - 通用：0 / 20.59 GB 🟢

【流量包明细】

🇨🇳国内通用流量
🔹[无忧卡-国内200MB流量]已用0KB/共200.00MB
🔹[无忧卡-国内200MB流量]已用0KB/共200.00MB
🔹[5G升级会员10G包9元201910]已用0KB/共10.00GB
🔹[网龄合约-100M流量优惠包（12个月）]已用0KB/共100.00MB
🔹[5G升级会员10G包9元201910]已用0KB/共10.00GB
🔹[网龄合约-100M流量优惠包（12个月）]已用0KB/共100.00MB

查询时间：2024-12-02 23:59:59

**Comment by Cp0204** [comment]
没有样本，判断不出问题，能否提供出错的手机和密码供调试（可以改一个临时密码）？ 发我主页的邮箱。

**Comment by 457084333** [comment]
这封邮件是自动回复的吗？手机和密码已经写在邮件里面了。
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月3日(星期二) 晚上8:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cp0204/ChinaTelecomMonitor] 不限量套查询流量报错 (Issue #16)














 
没有样本，判断不出问题，能否提供出错的手机和密码供调试（可以改一个临时密码）？ 发我主页的邮箱。

**Comment by Cp0204** [comment]
> 这封邮件是自动回复的吗？手机和密码已经写在邮件里面了。

噢噢，我刚没看邮件。收到了，不过密码似乎错误，登录失败。

**Comment by 457084333** [comment]
你再试试，难道没成功，刚才又改了一次，我试了下，可以登录了。&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月3日(星期二) 晚上8:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cp0204/ChinaTelecomMonitor] 不限量套查询流量报错 (Issue #16)














  
这封邮件是自动回复的吗？手机和密码已经写在邮件里面了。
  
噢噢，我刚没看邮件。收到了，不过密码似乎错误，登录失败。

**Comment by 457084333** [comment]
重新拉完了，运行，提示这个。懵逼## 开始执行... 2024-12-03 21:57:21 /ql/shell/otask.sh: line 96: cd: ChinaTelecomMonitor: No such file or directory python3: can't open file '/ql/data/scripts/telecom_monitor.py': [Errno 2] No such file or directory ## 执行结束... 2024-12-03 21:57:22  耗时 1 秒　　　　　
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月3日(星期二) 晚上9:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Cp0204/ChinaTelecomMonitor] 不限量套查询流量报错 (Issue #16)














 
好了，青龙重新拉一下订阅

**Comment by Cp0204** [comment]
> 发给ai，解决了，谢谢。 这个错误提示是说在使用 f-string 时出现了语法错误，具体是因为使用了不匹配的方括号&nbsp;[。在 Python 的 f-string 中，如果需要在字符串中使用&nbsp;{}&nbsp;来表示变量或表达式，而&nbsp;{}&nbsp;内部也包含方括号&nbsp;[]，则可能会导致解释器无法正确解析。 在你的代码中，important_data["responseData"]["data"]&nbsp;这种写法导致了问题。解决方法是使用额外的花括号&nbsp;{}&nbsp;来包裹内部的表达式。你可以修改你的代码为： python f"简化主要信息出错，提 Issue 请提供以下信息（隐私打码）：\n\n{important_data['responseData']['data']}\n\n{e}" 注意使用单引号&nbsp;'&nbsp;来包住字典的键，这样就不会与外部的 f-string 语法产生冲突了。这样就可以正常拼接字符串而不会引发语法错误。 &nbsp; &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2024年12月3日(星期二) 晚上9:14 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Cp0204/ChinaTelecomMonitor] 不限量套查询流量报错 (Issue #16) 好了，青龙重新拉一下订阅 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

好的这个问题也修了
