### ISSUE TITLE
福建电信不限量套餐报错

### ISSUE THREAD

**Issue by yuanhuat** [Cp0204/ChinaTelecomMonitor#19]
依赖应该没问题，我按照代码装的，可能是接口不一样。可以提供完整日志
![4310be4a87fc99d170a3a648a983f13](https://github.com/user-attachments/assets/53562b40-31c2-4c9b-ae2a-497eb44d3746)

**Comment by Cp0204** [comment]
https://github.com/Cp0204/ChinaTelecomMonitor/issues/7

**Comment by yuanhuat** [comment]
1179736569@qq.com请作者联系我提供token或user
