### ISSUE TITLE
summary = telecom.to_summary(important_data["responseData"]["data"]) bug

### ISSUE THREAD

**Issue by soapffz** [Cp0204/ChinaTelecomMonitor#2]
自动登录：成功
获取主要信息：成功
Traceback (most recent call last):
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 176, in <module>
    main()
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_monitor.py", line 122, in main
    summary = telecom.to_summary(important_data["responseData"]["data"])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ql/data/scripts/Cp0204_ChinaTelecomMonitor/telecom_class.py", line 212, in to_summary
    special_use = int(data["flowInfo"]["specialAmount"]["used"])
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

## 执行结束...   耗时 2 秒

**Comment by Cp0204** [comment]
你的套餐里是不是没定向流量？套餐不一样，可能返回不一样，而我只能根据我返回的数据来写，没有足够的样本，不好去猜。

瞄了下你博客，不少python文章😌，如果你熟悉py，根据你的返回兼容一下数据解析，欢迎解决后PR。

如果未能解决，也可打印一下 important_data["responseData"]["data"] 或者把电信账号密码发我邮箱。

**Comment by Cp0204** [comment]
重新拉取试试

**Comment by laceeeeee** [comment]
你好大佬，青龙拉取最新脚本后还是会报错
![微信截图_20240612101926](https://github.com/Cp0204/ChinaTelecomMonitor/assets/112396389/bca65aa3-4bfa-4ac5-8129-5672831f7cad)
流量就是正常的套餐包月流量，非定向流量。

**Comment by Cp0204** [comment]
> 你好大佬，青龙拉取最新脚本后还是会报错
> 流量就是正常的套餐包月流量，非定向流量。

没有样本，能不能提供一下账号密码或token（token重新登陆旧的就会失效）到我邮箱啊，不然只靠猜 😂 猜不到你们的数据返回是怎样的

**Comment by laceeeeee** [comment]
> > 你好大佬，青龙拉取最新脚本后还是会报错
> > 流量就是正常的套餐包月流量，非定向流量。
> 
> 没有样本，能不能提供一下账号密码或token（token重新登陆旧的就会失效）到我邮箱 Cp0204#qq.com 啊，不然只靠猜 😂 猜不到你们的数据返回是怎样的

好的，账号密码已发送至您的邮箱。

**Comment by Cp0204** [comment]
> > > 你好大佬，青龙拉取最新脚本后还是会报错
> > > 流量就是正常的套餐包月流量，非定向流量。
> > 
> > 
> > 没有样本，能不能提供一下账号密码或token（token重新登陆旧的就会失效）到我邮箱 Cp0204#qq.com 啊，不然只靠猜 😂 猜不到你们的数据返回是怎样的
> 
> 好的，账号密码已发送至您的邮箱。

收到

**Comment by Cp0204** [comment]
> > > 你好大佬，青龙拉取最新脚本后还是会报错
> > > 流量就是正常的套餐包月流量，非定向流量。
> > 
> > 
> > 没有样本，能不能提供一下账号密码或token（token重新登陆旧的就会失效）到我邮箱 Cp0204#qq.com 啊，不然只靠猜 😂 猜不到你们的数据返回是怎样的
> 
> 好的，账号密码已发送至您的邮箱。

已解决，重新拉取试试

**Comment by laceeeeee** [comment]
> > > > 你好大佬，青龙拉取最新脚本后还是会报错
> > > > 流量就是正常的套餐包月流量，非定向流量。
> > > 
> > > 
> > > 没有样本，能不能提供一下账号密码或token（token重新登陆旧的就会失效）到我邮箱 Cp0204#qq.com 啊，不然只靠猜 😂 猜不到你们的数据返回是怎样的
> > 
> > 
> > 好的，账号密码已发送至您的邮箱。
> 
> 已解决，重新拉取试试

感谢大佬~已完美~！！
