### ISSUE TITLE
查询登录报错（已解决，应用电信账号，而非天翼账号）

### ISSUE THREAD

**Issue by chenjiezb** [Cp0204/ChinaTelecomMonitor#8]
感谢cp0204提供的代码，我在试用过程中遇到问题，请求指点。
已经按说明部署好docker，在node-red中搭建POST request流程测试，访问本地API http://192.168.10.236:10000/login，debug输出如下：
msg.payload : Object
	object
	headerInfos: object
		code: "0000"
		reason: "操作成功"
	responseData: object
		resultCode: "1000"
		resultDesc: "请求失败"
		attach: ""
		data: null

以下是docker容器的日志：
 * Serving Flask app 'api_server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10000
 * Running on http://172.17.0.3:10000
Press CTRL+C to quit
192.168.10.138 - - [16/Jul/2024 22:15:55] "POST /login HTTP/1.1" 400 -
192.168.10.138 - - [16/Jul/2024 22:16:17] "POST /login HTTP/1.1" 400 -
192.168.10.138 - - [16/Jul/2024 22:17:04] "POST /login HTTP/1.1" 400 -

我所查询的江苏电信的电话卡，一样的卡号和密码在官网登录正常。

**Comment by Cp0204** [comment]
从信息中判断不出什么问题，直接调用接口看下原文，尤其是 headerInfos: object

**Comment by chenjiezb** [comment]
直接调用接口响应体如下：
{
  "headerInfos": {
    "code": "0000",
    "reason": "操作成功"
  },
  "responseData": {
    "resultCode": "1000",
    "resultDesc": "请求失败",
    "attach": "",
    "data": null
  }
}

**Comment by chenjiezb** [comment]
我可以提供账号密码供大佬测试，请给个邮箱

**Comment by Cp0204** [comment]
> 我可以提供账号密码供大佬测试，请给个邮箱

Cp0204@qq.com

**Comment by chenjiezb** [comment]
> [Cp0204@qq.com](mailto:Cp0204@qq.com)

已发

**Comment by Cp0204** [comment]
已邮箱沟通解决。

应使用电信账号密码（密码格式是6位数字），能登陆“中国电信”APP为准，而非天翼账号，特此做记录，供后人参考。
