### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by chendada00** [Cp0204/ChinaTelecomMonitor#9]
![image](https://github.com/user-attachments/assets/e18483d5-ce96-4735-9dbf-e710f25a08b5)
啥问题，是因为我的青龙版本太低么2.15.9

**Comment by chendada00** [comment]
貌似还是有问题
![image](https://github.com/user-attachments/assets/327fcb24-b56e-4cb3-9240-aca9ec197735)

**Comment by chendada00** [comment]
貌似还是有问题
![image](https://github.com/user-attachments/assets/74350533-b772-4d17-a7c9-d7570543fdca)

**Comment by Cp0204** [comment]
重新拉一遍试下？

**Comment by chendada00** [comment]
这个密码是什么，是服务密码吗

**Comment by Cp0204** [comment]
> 这个密码是什么，是服务密码吗

https://github.com/Cp0204/ChinaTelecomMonitor/issues/8#issuecomment-2232566544
